apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  labels: 
    project: roboshop 
    component: frontend 
    tier: frontend
spec:
  containers:
  - name: nginx
    image: nginx  
    ports:
    - containerPort: 80    